version: '2'

services:
  database_pandora_2:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=pandora_api
      - MARIADB_PASSWORD=pandora_33klwZ_76
    ports:
      - 3307:3306
    volumes:
      - mydb-db-api:/var/lib/mysql
  pandora:
    tty: true
    image: jjuanrivvera99/ubuntu-apache-php-sqlserver
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=database_pandora_2
      - DB_USERNAME=admin
      - DB_DATABASE=pandora_api
      - DB_PASSWORD=pandora_33klwZ_76
      - APP_DEBUG=true
      - APP_ENV=local
      - APP_KEY=base64:gpy5yuVmMykxrpIqfovUFu84rcdFJMAYEyoFs/xxyuo=
      - DB_HOST_GP=SRVWMSTEST.COLSEIN.COM.CO
      - DB_USERNAME_GP=sa
      - DB_DATABASE_GP=Pandora
      - DB_PASSWORD_GP=t3St#2021**
      - APP_ENV=production
    depends_on:
      - database_pandora_2
    ports:
      - 9002:80
    volumes:
      - ./:/var/www/
    # privileged: true # Privileged mode could be required to run this container under Windows
    # 
volumes:
  mydb-db-api:
