version: '3.5'

services:
  app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: app
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - .:/var/www/html
    ports:
      - 9002:80
    networks:
      backend:
        aliases:
          - app

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./run/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=33klwZ_76
      - MYSQL_DATABASE=pandora
      - MYSQL_USER=root
      - MYSQL_PASSWORD=33klwZ_76
    ports:
      - 3307:3306
    networks:
      backend:
        aliases:
          - db

networks:
  backend:
    name: backend-network
