version: '2'

services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.2-debian-10'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=admin
      - MARIADB_DATABASE=pandora_api
      - MARIADB_PASSWORD=33klwZ_76
    ports:
      - 3307:3306
    volumes:
      - ./database-docker:/var/lib/mysql
  myapp:
    tty: true
    image: docker.io/bitnami/laravel:7-debian-10
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=admin
      - DB_DATABASE=pandora_api
      - DB_PASSWORD=33klwZ_76
    depends_on:
      - mariadb
    ports:
      - 9002:3000
    volumes:
      - ./:/app
    # privileged: true # Privileged mode could be required to run this container under Windows
    # 