version: '3'

services:
  app:
    build: .
    image: pandora-app
    depends_on:
      - mysql
    volumes:
      - ./:/application:cached

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=33klwz_76
      - MYSQL_DATABASE=pandora
    volumes:
      - db-data:/var/lib/mysql:cached

  nginx:
    image: nginx:alpine
    ports:
      - "9002:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/application:cached
    depends_on:
      - app

volumes:
  db-data: